# Generated by Django 5.0.1 on 2024-02-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contained_signs', models.ManyToManyField(related_name='signs', to='signs.sign')),
            ],
        ),
    ]
