# Generated by Django 5.0.1 on 2024-02-14 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_set'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='sign',
            name='handshape',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='sign',
            name='palm_orientation',
        ),
        migrations.AddField(
            model_name='demonstration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sign',
            name='tags',
            field=models.ManyToManyField(to='signs.tag'),
        ),
    ]
