# Generated by Django 5.0.1 on 2024-04-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0003_tag_remove_sign_handshape_remove_sign_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='tags',
            field=models.ManyToManyField(null=True, to='signs.tag'),
        ),
    ]
