# Generated by Django 5.0.1 on 2024-04-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0004_alter_sign_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='signs.tag'),
        ),
    ]
